name: Dependency Updates
on:
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check for dependency updates
        run: ./gradlew dependencyUpdates

      - name: Generate dependency update report
        id: deps
        run: |
          if [ -f "build/dependencyUpdates/report.txt" ]; then
            echo "updates_available=true" >> $GITHUB_OUTPUT
            echo "report_content<<EOF" >> $GITHUB_OUTPUT
            cat build/dependencyUpdates/report.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "updates_available=false" >> $GITHUB_OUTPUT
          fi

      - name: Create dependency update PR
        if: steps.deps.outputs.updates_available == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "deps: automated dependency updates"
          title: "🔄 Automated Dependency Updates"
          body: |
            ## 🔄 Automated Dependency Updates
            
            This PR contains automated dependency updates detected by the weekly scan:
            
            ```
            ${{ steps.deps.outputs.report_content }}
            ```
            
            ### ✅ Checklist
            - [ ] Review dependency changes
            - [ ] Test the application
            - [ ] Check for breaking changes
            - [ ] Verify security updates
            
            ---
            *This PR was automatically created by the dependency update workflow*
          branch: deps/automated-updates-${{ github.run_number }}
          base: main
          delete-branch: true