name: Performance Monitoring
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Analyze APK size
        run: |
          APK_SIZE=$(stat -c%s "app/build/outputs/apk/debug/app-debug.apk")
          echo "APK_SIZE_BYTES=$APK_SIZE" >> $GITHUB_ENV
          echo "APK size: $(($APK_SIZE / 1024 / 1024)) MB"

      - name: Comment APK size on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const apkSize = parseInt(process.env.APK_SIZE_BYTES);
            const sizeMB = (apkSize / 1024 / 1024).toFixed(2);
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📱 **APK Size Report**\n\n- Debug APK size: **${sizeMB} MB**\n- Size in bytes: ${apkSize.toLocaleString()}`
            });

      - name: Run benchmark tests
        run: ./gradlew connectedDebugAndroidTest

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: app/build/reports/androidTests/connected/