name: Post-Release Updates
on:
  release:
    types: [published]

jobs:
  update-documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      - name: Update CHANGELOG.md
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}
          path-to-changelog: CHANGELOG.md

      - name: Update README.md version
        uses: MathieuSoysal/file-updater-for-release@v1
        with:
          files: README.md
          prefix: "musclab@"
          with-checkout: false

      - name: Update version in build.gradle
        run: |
          # Extract version number from tag (remove 'v' prefix)
          VERSION="${{ github.event.release.tag_name }}"
          VERSION_NAME="${VERSION#v}"
          VERSION_CODE=$(date +%s)
          
          # Update app/build.gradle.kts
          sed -i "s/versionName = \".*\"/versionName = \"$VERSION_NAME\"/" app/build.gradle.kts
          sed -i "s/versionCode = .*/versionCode = $VERSION_CODE/" app/build.gradle.kts

      - name: Create documentation update PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update documentation for ${{ github.event.release.tag_name }}"
          title: "📚 Documentation updates for ${{ github.event.release.tag_name }}"
          body: |
            ## 📚 Automated Documentation Updates
            
            This PR contains automated updates following the release of ${{ github.event.release.tag_name }}:
            
            - ✅ Updated CHANGELOG.md with release notes
            - ✅ Updated README.md version references
            - ✅ Updated build.gradle version numbers
            
            ### Release Notes
            ${{ github.event.release.body }}
            
            ---
            *This PR was automatically created by the post-release workflow*
          branch: docs/update-${{ github.event.release.tag_name }}
          base: main
          delete-branch: true